# Generated by Django 5.2 on 2026-03-13 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_newsarticle_image_url_alter_newsarticle_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
