# Generated by Django 5.2 on 2026-03-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-imported_at']},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='edited_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='paraphrased_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to Publish'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
