# Generated by Django 5.2 on 2026-03-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_newsarticle_options_newsarticle_edited_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_at', '-imported_at']},
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='edited_content',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='paraphrased_content',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='status',
        ),
    ]
