# Generated by Django 5.2 on 2026-03-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_newsarticle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-imported_at']},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - Ready to Edit'), ('ready', 'Ready to Publish'), ('published', 'Published to Blog')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=models.CharField(blank=True, default='news', max_length=500),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
