# Generated by Django 5.2 on 2026-03-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_newsarticle_options_newsarticle_ai_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='External image URL from news sources', max_length=1000),
        ),
    ]
